### ISSUE TITLE
Button not showing after Startpage redesign

### ISSUE THREAD

**Issue by Teriy-Aki** [maxmmueller/startpage-maps#1]
Hello Max,

I wanted to inquire if Opera support could be possible? Your extension sounds great but I don't think it works on Opera. I managed to Install it (altough with an error) 
![image](https://github.com/maxmmueller/startpage-maps/assets/29336917/837610f1-2e5b-4256-b4cf-cda0893545f6)
 and I enabled access to searchpage results, but the maps tab does not show up.

Support would be greatly appreciated.

**Comment by maxmmueller** [comment]
Hey Teriy-Aki, 
Thanks for pointing out this bug! I've been quite inactive in this repo for a couple of months now and haven't been using Startpage myself during that period. The problem isn't connected to your Opera browser, but rather to the design changes that Startpage went through. I've adjusted the code accordingly. The button isn't matching the new style/design completely but it provides the basic functionality which should work for now.

Please let me know if you need more help in the future!

**Comment by Teriy-Aki** [comment]
Hey Max,

I tried the extension again with your recent changes and I'm happy to report the extension works again, in Opera too! Thank you for the update and for being so kind in the support.
